version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/app/Dockerfile
      args:
        JAR_FILE: ${JAR_FILE}
    ports:
      - "${APP_PORT}:8080"
    networks:
      main:

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command:
      - start-dev
      - --db=postgres
      - --db-url=jdbc:postgresql://${AUTH_DB_HOST}:${AUTH_DB_PORT}/${AUTH_DB_NAME}
      - --db-username=${AUTH_DB_USER}
      - --db-password=${AUTH_DB_PASSWORD}
      - --import-realm
    ports:
      - "${KEYCLOAK_PORT}:8080"
    networks:
      main:
    volumes:
      - ./docker/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - postgres_auth
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USERNAME}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}

  postgres_auth:
    image: postgres:latest
    ports:
      - "${AUTH_DB_PORT}:5432"
    volumes:
      - postgres-auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_DB=${AUTH_DB_NAME}

networks:
  main:
    driver: bridge

volumes:
  postgres-auth:
